name: Release QGIS Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install pb_tool
    
    - name: Build plugin
      run: |
        pb_tool zip
    
    - name: List files
      run: ls -la
    
    - name: Find zip file
      id: find_zip
      run: |
        ZIP_FILE=$(find . -name "*.zip" -type f -printf "%f\n")
        echo "ZIP_FILE=${ZIP_FILE}" >> $GITHUB_ENV
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ZIP_FILE }}
        name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}